### PR TITLE
Add completion for ninja build system

### PR DESCRIPTION
**Pull request by bsott**
I created a simple completion for ninja build system

### CODE REVIEW

**Comment by sagebind** [comment]
@bsott Sorry for the delay, looks like we missed this PR. Looks good to me, thanks for wanting to put the plugin in the official database!

Also, would you like to have your plugin repository in Oh My Fish organization? It is by no means required, but it helps keep compatible packages in a central search place. If you're interested, please update this PR with the URL https://github.com/oh-my-fish/plugin-ninja and I will allocate a repository and make you an admin, and you can use it as upstream.

**Comment by bobthecow** [comment]
For completions, we strongly recommend opening a PR to add them to the core Fish codebase. They're very responsive and adding them there benefits everyone automatically :)

**Comment by bsott** [comment]
@sagebind the URL is updated, does it makes sense to skip the omf step as @bobthecow suggest?

**Comment by sagebind** [comment]
@bsott If the plugin is just completions, yeah perhaps consider adding them to Fish itself.

If you decide to do so, let us know and we can cancel this PR.

**Comment by bsott** [comment]
It's merged in fish, closing.

**Comment by sagebind** [comment]
@bsott Awesome!

**Comment by bobthecow** [comment]
🎉

**Pull request closed without merging**
