### PR TITLE
Added a new theme `es` with properly formatted remote name 

### PR DESCRIPTION
**Pull request by eugenesvk**
https://github.com/eugenesvk/omf-theme-es
Per https://github.com/oh-my-fish/oh-my-fish/pull/244 didn't change `Readme.md`.

### CODE REVIEW

**Comment by derekstavis** [comment]
Awesome! Thanks for the theme!! As this is now merged, you can remove the original repository. You are admin on https://github.com/oh-my-fish/theme-es. This would avoid confusion and duplication :+1:

**Comment by eugenesvk** [comment]
@derekstavis ok, thanks!

Just last two minor questions:
1. I have a few custom functions that I'd like to include in the theme without polluting the clean list of 3 functions (greeting, prompt, title) in the main theme folder. Can I include those in `.../es/Functions` instead of `.../es` or will your tool not understand it and won't be able to symlink them to the main `.config/fish/functions` during installation? If not I'll just add them to the main path.

2. How do I add a screenshot without it appearing as a separate file in the repo — I've noticed other themes have this in the overall `readme.md` without having a screenshot in the repo itself.
Not a big deal, will just copy them to the main repo path, just a tad curious.
Thanks

**Comment by derekstavis** [comment]
1. Themes currently does not support `functions` directory. You can put additional functions in repository root path.
1. To add screenshots without adding actual files to repository you need to use Github editor and drag files into it, this way they will be uploaded to Github without adding files to the repository.

**Comment by eugenesvk** [comment]
Thanks for clarifications!
I'll also update the `readme.md` file with a short description of the functions — would that automatically be merged to the consolidated `readme.md` file or would I have to ping you somehow on update?

**Comment by derekstavis** [comment]
I will update the Themes docs as soon as I hit my computer. If you plan to add more stuff to your README please tell me and also ping me when you are ready to go!

**Comment by eugenesvk** [comment]
Hey, I've updated the `Readme.md` file, so feel free to add it to the consolidated file. Don't plan to change it in the near term.

**Comment by eugenesvk** [comment]
Hey, I've updated the `Readme` file again to add another screenshot (showing a 'lock' icon in read-only folders). Feel free to adjust the consolidated `Readme` if you like.

**Pull request merged**
