### PR TITLE
refact(pkg/thefuck): use a better, oh-my-fishy thefuck plugin

### PR DESCRIPTION
**Pull request by scorphus**
We're good to go using our very own thefuck plugin. OMF FTW! Please review, and comment, these are much welcome.

### CODE REVIEW

**Comment by bucaran** [comment]
Would be better to send a PR to the original package with your changes instead of creating a new package. 

The maintainer there is @gretel

**Comment by gretel** [comment]
i don't think having duplicate packages is a good idea, too. regards

**Comment by derekstavis** [comment]
:+1: for the merge.

**Comment by bpinto** [comment]
Unfortunately the plugin @scorphus submitted is already using the [new architecture](https://github.com/oh-my-fish/oh-my-fish/issues/8).

**Comment by scorphus** [comment]
@bpinto said:
> The plugin @scorphus submitted is a new plugin that uses the new architecture, which is required by the revamped omf.

Yeah, there's this incompatibility issue...

@bucaran said:
> Maybe better to send a PR to the original package with your changes instead of creating a new package?
> 
> @gretel

... so I opened wa/pkg-thefuck#1 as well.

@bpinto said:
> Thanks for the contribution @scorphus!

Always a pleasure :+1:

**Comment by bpinto** [comment]
:dancers: :tada:

**Comment by bucaran** [comment]
@bpinto Oh, so you are not sourcing `<package name>/<package name>.fish` anymore?

**Comment by bpinto** [comment]
We won't source that file anymore, it's only sourcing for backwards compatibility.

**Pull request merged**
