### PR TITLE
add artisan

### PR DESCRIPTION
**Pull request by thecotne**

### CODE REVIEW

**Comment by derekstavis** [comment]
Hi @thecotne. Thanks for the PR! By default Oh My Fish repository names must start with `plugin-` and themes with `theme-`. Would you mind fixing this issue before we merge this package into db?

**Comment by thecotne** [comment]
@derekstavis why does repository name matter? 
i don't want to change my repository name to `plugin-artisan` because it does not tell anything about repository

it is oh my fish (omf) plugin for artisan so i named it accordingly

i can rename it to omf-plugin-artisan if you want to mention plugin in repository name
but i don't want to remove omf prefix since it is not plugin for everything that exists and may exist in future it is only for omf

also i looked at db and find out that many plugins does not follow this convention there are pkg prefixed and omf prefixed repository's

**Comment by derekstavis** [comment]
> why does repository name matter?

1. Standardization
2. Differentiate different package types
3. It's [a Oh My Fish rule](https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/cli/omf.install.fish#L22)

> also i looked at db and find out that many plugins does not follow this convention

There are no plugins which does not follow this convention: `basename -a (cat $OMF_PATH/db/pkg/*)`

>... there are pkg prefixed and omf prefixed repository's 

`pkg-` is supported for backwards compatibility.

> i can rename it to omf-plugin-artisan if you want to mention plugin in repository name

There are an open issue about this at #152. I would be glad to accept PRs implementing it.

**Comment by bpinto** [comment]
I totally missed this, is this ready @thecotne ?

**Comment by thecotne** [comment]
@bpinto nope it has `omf-` prefix

**Comment by bpinto** [comment]
:+1:

**Comment by oranja** [comment]
@thecotne **omf-** prefix is supported now. Want to rebase your PR so this can be merged?

**Comment by bpinto** [comment]
Thanks! Plugin added!

**Pull request closed without merging**
