### PR TITLE
Include update instructions

### PR DESCRIPTION
**Pull request by derekstavis**
This PR adds manual update instructions to main README. It's very important, as various issues emerged in last days (see #33, #7, oh-my-fish/plugin-rbenv#6) and we need a central place to put this instructions, instead of copy-pasting them into issues.

### CODE REVIEW

**Comment by mrThe** [comment]
Please, add there information about changing git remote origin url. It's very important step.

**Comment by derekstavis** [comment]
Done @mrThe

**Comment by derekstavis** [comment]
@oh-my-fish/core any thoughts on this?

**Comment by bpinto** [comment]
I don't like steps 6/7/8 as they are complex, I think we can do better by automating these steps. However we need this asap.

:+1:

**Comment by derekstavis** [comment]
You mean we can merge the upgrade or we need to hurry on supporting old config?

**Comment by bpinto** [comment]
I'd merge the documentation and work on the code to remove these steps.

**Pull request merged**
