### PR TITLE
Add kill-on-port pkg

### PR DESCRIPTION
**Pull request by vincentjames501**
Is there a good way of specifying transient dependencies? This pkg requires the getopts pkg for example...?

### CODE REVIEW

**Comment by vincentjames501** [comment]
Ah. +1 on #64 :+1:

**Comment by derekstavis** [comment]
As `getopt` comes alphabetically before `kill-on-port` you have no issues. We are working in solving dependencies in a declarative way instead of imperative, which should also auto-install them. Although not very recommended, you can do what I've done on `foreign-env` package.

**Comment by bpinto** [comment]
Very interesting plugin!

**Comment by bobthecow** [comment]
> As getopt comes alphabetically before kill-on-port you have no issues. 

Is this guaranteed, or does it depend on having a filesystem that returns directories in alphabetical order?

**Comment by derekstavis** [comment]
I think it depends more on how the shell expands the directory listing.

**Pull request merged**
