### PR TITLE
Make `generate-themes-doc` usable and update Themes.md

### LINKED ISSUE #795: `tools/generate-themes-doc.fish` is broken.
It's still assuming that the package metadata is located in the project directory. I hacked up a version that would regenerate based on my current `omf.index.path` location, but that doesn't seem ideal.

Maybe we have it check out the repo in a temporary location and regenerate from HEAD?

### PR DESCRIPTION
**Pull request by scorphus**
I didn't have much time to invest in `tools/generate-themes.doc.fish`, unfortuntely. It's far from perfect, but fairly usable. Please, refer to instructions in the header.

Fix #795, #800, #771

### CODE REVIEW

**Comment by bobthecow** [comment]
I think the list of themes at the top is getting unmanageable. We should probably just remove it and let people scroll through the doc :)

**Review by bobthecow — APPROVED** [review]
:shipit:

**Comment by scorphus** [comment]
Hey, @bobthecow 👋 Glad to have you.

Thanks for the review, for the approval and merge.

Yeah, I also had my eye caught by that.

I was thinking about doing something like this:

<details>
  <summary><b>Expand for the complete list of themes</b></summary>

* [bar1](#bar)
* [bar2](#bar)
* [baz1](#baz)
* [baz2](#baz)
* [foo1](#foo)
* [foo2](#foo)
* [qux1](#qux)
* [qux2](#qux)

</details>

Or even something more compact:

<details>
  <summary><b>Expand for the complete list of themes</b></summary>

| **[bar1](#bar)** | **[baz1](#baz)** | **[foo1](#foo)** | **[qux1](#qux)** |
|---|---|---|---|
| **[bar2](#bar)** | **[baz2](#baz)** | **[foo2](#foo)** | **[qux2](#qux)** |

</details>

What do you think?

**Comment by bobthecow** [comment]
Both great options. Let's try the second and see how it feels?

**Pull request merged**
