### PR TITLE
Tiny text improvements

### PR DESCRIPTION
**Pull request by demidovakatya**

### CODE REVIEW

**Comment by oranja** [comment]
Nice. Proper English always makes me feel more comfortable with a project.

**Comment by derekstavis** [comment]
Thanks for the improvements, they are very welcome! You need to rebase the commits on current master, as we already removed upgrade instructions from README. I can merge as soon as you resolve this conflict. Thanks again :smile:

**Comment by demidovakatya** [comment]
@derekstavis being honest, I have some troubles with rebasing. Could you tell me how to rebase correctly? :cherries:

**Comment by derekstavis** [comment]
Yes @demidovakatya. The steps I usually do is:

1. `git checkout master`
1. `git pull upstream master`
1. `git rebase master <your branch>`
1. Solve possible conflicts in files
1. `git add .`
1. `git rebase --continue`
1. Conflicts? Go back to 4, else you are done
1. `git push <your remote> <your branch>`

This should be sufficient. Feel free to join us on Slack if you continue finding problems :+1:

**Comment by derekstavis** [comment]
(Sorry, mistakenly closed)

**Comment by demidovakatya** [comment]
I still have problems with `rebase`, but no more conflicts, right?

Thanks for your help, guys! :sunny:

**Comment by derekstavis** [comment]
I will rebase them for you. Thanks for your efforts!

**Comment by derekstavis** [comment]
You got it @demidovakatya

**Comment by demidovakatya** [comment]
:balloon: :balloon:

**Pull request merged**
