### PR TITLE
registry: add rafaelrinaldi/theme-pure

### PR DESCRIPTION
**Pull request by oranja**
Following oh-my-fish/#227, @rafaelrinaldi @edouard-lopez joined forces to make the upstream repository compatible with OMF, including a "theme-pure" alias.
**[pure]** can now join the family of OMF's registered themes. :tada: 

[pure]: rafaelrinaldi/pure

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@oranja Let me know if I can help fixing the CI error. Looks like an issue related to repo name?

**Comment by derekstavis** [comment]
@oranja, you have to run `tools/generate-themes-doc.fish` to update theme documentation. @rafaelrinaldi if you do have updates to do on README this is the moment. Your README will be copied to [Themes list](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md).

**Comment by oranja** [comment]
Thanks @derekstavis.
Ran into a small problem. See #232.

**Comment by edouard-lopez** [comment]
@oranja I'm editing the doc to fix the path to the theme to 

    omf install pure

**Comment by oranja** [comment]
Wonderful. I hope that this PR will be merged in a matter of a few hours..

**Comment by derekstavis** [comment]
Most database themes doesn't include .git suffix. We try to keep this pattern. Would you mind removing the `.git` suffix before we merge?

**Comment by oranja** [comment]
I will, but I think it should be the other way around.
Setting the standard to drop the '.git' will make it harder to support
BitBucket/Gitlab/etc repositories in the future. (Perhaps BB/GL already
support URLs without the .git suffix. I'm not near a computer to check)

>

**Pull request merged**
