### PR TITLE
Add dpaste

### PR DESCRIPTION
**Pull request by rominf**
Supersedes #430

### CODE REVIEW

**Comment by derekstavis** [comment]
Oh, I missed this one! Let's merge it! Would you mind rebasing this on master?

**Comment by bobthecow** [comment]
No need to rebase. We can merge as-is.

**Comment by abhigenie92** [comment]
```
$ omf install dpaste                                       
Installing package dpaste
fatal: repository 'dpaste' does not exist
Could not install package dpaste.
$ omf --version                                                         
Oh My Fish version 3

```

Can you please add it.

**Comment by sagebind** [comment]
@abhigenie92 It was added. Be sure to update OMF to get new package releases. If you're on the `stable` release channel, you need to switch to `dev` since this plugin has not been included in a release since.

**Comment by abhigenie92** [comment]
Using the repo. from github.
```
$ omf install dpaste
Installing package dpaste
fatal: unable to access 'https://github.com/oh-my-fish/plugin-dpaste /': The requested URL returned error: 400
Could not install package dpaste.
```

**Comment by sagebind** [comment]
@abhigenie92 Oops, my bad, looks like the PR author had an extra space in the URL. Fixed in #460.

**Pull request merged**
