### PR TITLE
Added a new theme named cyan

### PR DESCRIPTION
**Pull request by szwathub**
https://github.com/szwathub/omf-theme-cyan
can get more information about time since last commit and so on.
IMG

### CODE REVIEW

**Comment by derekstavis** [comment]
Hey @szwathub, would you like me to allocate a repo inside Oh My Fish organization for you to move your theme? This way you will be part of the organization and will continue as an admin of your repo. We offer repos inside the organization to make easier to find new themes and plugins in a central place.

**Comment by szwathub** [comment]
Yes, please allocate a repo inside Oh My Fish organization. 
Thanks

**Comment by szwathub** [comment]
if possible, please rename it as theme-qing
Thanks

**Comment by derekstavis** [comment]
Just allocated the repo at https://github.com/oh-my-fish/theme-qing

Feel free to push the theme there and adjust this PR.

Be sure to add the HTTPS URL to the database file, removing the trailing .git

Welcome to the organization!

**Comment by szwathub** [comment]
Thanks.

**Comment by derekstavis** [comment]
Feel free to remove the original repository to avoid confusion and revision mismatch. I will be merging your PR. Thanks for the addition!!

**Pull request merged**
