### PR TITLE
Remove vscode plugin

### PR DESCRIPTION
**Pull request by mathiasvr**
VSCode can now add the `code` command to PATH by itself.

### CODE REVIEW

**Comment by derekstavis** [comment]
Cool, thanks for being an awesome maintainer!!

**Comment by derekstavis** [comment]
Since Oh My Fish doesn't uninstall plugins which are removed from database, you could also add a deprecation message to the plugin, for example:

```
$ code
The `vscode` Oh My Fish plugin is deprecated!
Since Visual Studio Code 1.0 the command `code` is natively available.
You can safely `omf remove vscode` to use the native command.
```

**Comment by bobthecow** [comment]
What @derekstavis said. I came here to say the same thing :)

**Comment by mathiasvr** [comment]
Thank you, I have pushed the changes here https://github.com/oh-my-fish/plugin-vscode/commit/8eac1ae2b482eef0abe5a37fe91f9bdf6d906705.

**Comment by derekstavis** [comment]
Thanks!

**Pull request merged**
