### PR TITLE
Add a new theme: Sushi.

### PR DESCRIPTION
**Pull request by umayr**
This PR adds a new theme named [Sushi](https://github.com/umayr/theme-sushi/).

#### Features

* Minimal Prompt.
* Git Support.
* Displays `^` when there are stashed changes.
* Displays `*` when there are any changes to files already being tracked in the repo.
* Displays current branch name.
* Branch name color changes when there are staged changes.
* Displays number of commits current branch is ahead/behind from origin.
* By default it shows only the name of the current directory but it provides a flag `theme_complete_path` to display abbreviated current working directory instead.
* Displays Time.

#### Screenshot

Screenshot for Sushi Theme

### CODE REVIEW

**Comment by derekstavis** [comment]
Nice theme! Thanks a lot for submitting it!

I see just one fix in your theme repository: Our template for themes is currently wrong (will be fixed when #128 gets merged), so where in your README reads

```
omf u sushi
```

It should be adjusted to 

```
omf install sushi
```

Other than this little fix, I'm :+1: for the merge. And thanks again!

**Comment by umayr** [comment]
Hey @derekstavis,

Yeah, I was wondering about it too. Anyway, it has been fixed in theme's `readme.md` as well as in the `docs/Themes.md`.

Let me know if there's still anything wrong.

**Comment by derekstavis** [comment]
Your branch is out-of-date with our master, can you please rebase it before we merge it? Thanks!!

**Comment by umayr** [comment]
@derekstavis Done.

**Comment by derekstavis** [comment]
Nice. :+1: for the merge @bpinto @bobthecow

**Pull request merged**
