### PR TITLE
Adds the exenv package

### PR DESCRIPTION
**Pull request by douglascamata**
Simple package to make exenv play nice with fish-shell.

### CODE REVIEW

**Comment by derekstavis** [comment]
Hey, would you like to migrate your repository to Oh My Fish organization? I can arrange a repository for you and make you an admin! You will have full control over the repository.

**Comment by douglascamata** [comment]
@derekstavis sure, no problem. 👍

**Comment by douglascamata** [comment]
@derekstavis package url adjusted.

**Comment by derekstavis** [comment]
Cool. :tada:  Merging as soon as Travis succeed.

You can remove the original repository to avoid confusion and keep working on organization's one.

Thanks for contributing and welcome to the organization!

**Comment by douglascamata** [comment]
@derekstavis thank you very much! It's an honor to be part of the organization. I hope I can contribute more soon.

**Pull request merged**
