### PR TITLE
Regenerate Themes.md

### PR DESCRIPTION
**Pull request by bobthecow**
# Description

- Add barracuda and solarfish
- Update bobthefish readme contents

### CODE REVIEW

**Comment by scorphus** [comment]
That script can be simplified a bit more. I'll update it ASAP.

🐠🐚

**Review by bobthecow — COMMENTED** [review]
I can't approve it, because it's my change apparently, but looks good to me :)

**Review by scorphus — APPROVED** [review]

**Comment by scorphus** [comment]
:shipit: 

Thanks, @bobthecow 🙌

**Comment by bobthecow** [comment]
Thank _you_!

**Pull request merged**
