### PR TITLE
Add theme plain

### PR DESCRIPTION
**Pull request by changyuheng**

### CODE REVIEW

**Comment by derekstavis** [comment]
By OMF convention, the repository name must be prefixed with just "theme". In this case the correct URL should be `https://github.com/changyuheng/theme-plain`. You also don't need to prepend `.git` :)

**Comment by changyuheng** [comment]
Hi @derekstavis. Thanks for your clear guide. I've updated it.

**Comment by derekstavis** [comment]
When you have time, please rebase it from current master branch and we are ready to merge!

**Comment by changyuheng** [comment]
Hi @derekstavis, OK, done. Thank you.

**Comment by derekstavis** [comment]
Nice! LGTM @bpinto @bobthecow

**Comment by bpinto** [comment]
Thanks @changyuheng

**Pull request merged**
