### PR TITLE
Add autopath

### PR DESCRIPTION
**Pull request by fabianhjr**
A package to include common paths and removing the need to add them manually.

### CODE REVIEW

**Comment by bpinto** [comment]
@fabianhjr Could you rebase and ping me after? I'll merge it once it has been rebased.

**Comment by bpinto** [comment]
ping @fabianhjr

**Comment by fabianhjr** [comment]
pong @bpinto sorry; I have been a bit busy with schoolwork and want to do some further changes before it ispublish ready. C:

**Comment by oranja** [comment]
@fabianhjr can this be closed for now? submit a PR again when it's ready?

**Pull request closed without merging**
