### PR TITLE
Create mars

### PR DESCRIPTION
**Pull request by mvader**

### CODE REVIEW

**Comment by derekstavis** [comment]
Hi @mvader! Thanks for the theme!! Would you like to migrate the repository to Oh My Fish organization? I can allocate a repository for you and add you as admin. This way we centralize packages and ease the discovery.

**Comment by mvader** [comment]
Hi @derekstavis! Yes, I can migrate it to the Oh My Fish :)

**Comment by derekstavis** [comment]
Here we go!! Please push the theme to https://github.com/oh-my-fish/theme-mars and update the PR. I will be happy to merge it!! You can remove the original repository, as you are an admin. Welcome to Oh My Fish organization!! :tada:

**Comment by mvader** [comment]
Done! @derekstavis

**Comment by derekstavis** [comment]
Awesome!! Would you mind squashing into a single commit with the message "registry: add theme mars"? It's more descriptive for the history :)

**Comment by mvader** [comment]
Done! @derekstavis

**Comment by derekstavis** [comment]
Great work!! Also be welcome to join our [Slack](https://oh-my-fish-slack.herokuapp.com)! Merging as soon as Travis finishes! Thanks again!

**Comment by derekstavis** [comment]
Hey @mvader, can you rebase on current master? Let's merge!! :tada:

**Pull request merged**
