### PR TITLE
Check whether we are inside the worktree

### PR DESCRIPTION
**Pull request by krobelus**
Some git commands require to be run from inside the worktree (as opposed to the git dir, although it's usually in worktree/.git). This commit adds a function git_is_worktree to check this. It is used for the commands that need the worktree instead of git_is_repo.

An alternative solution might have been to find the git worktree in the parent of the git directory, but this doesn't work for all cases. Generally it's impossible to detect the location of the worktree (plus it's not unique).

### CODE REVIEW

**Review by faho — APPROVED** [review]
This LGTM, the merge conflict should be quite simple.

**Review by bobthecow — APPROVED** [review]
LGTM

**Review by scorphus — APPROVED** [review]
Thanks, @krobelus!

**Comment by scorphus** [comment]
If I haven't merged this when TravisCI finally gives it [a chance to build](https://www.traviscistatus.com/#system-metrics), feel free to act. I'd suggest you to use the "Squash and merge" button.

**Comment by faho** [comment]
> If I haven't merged this when TravisCI finally gives it a chance to build

Side note: You need to move away from Travis. See https://github.com/fish-shell/fish-shell/issues/7447

**Comment by scorphus** [comment]
Yep. I've done this for several other projects. Travis was so nice since the old days. But it was sold and since then it's been focusing more on enterprise contracts. It's GitHub actions FTW.

**Comment by bobthecow** [comment]
> You need to move away from Travis.

Yes.

**Pull request merged**
