### PR TITLE
Packages support

### PR DESCRIPTION
**Pull request by scorphus**
This pull request proposes some improvement regarding package listing and installing/updating.

### CODE REVIEW

**Comment by derekstavis** [comment]
This commit naming scheme drives me crazy :trollface:

**Comment by derekstavis** [comment]
Nice PR. Definitely fixes the issues I have here @scorphus.

**Comment by derekstavis** [comment]
Perhaps you may also be interested in giving a look at [merge-theme-and-install](https://github.com/derekstavis/oh-my-fish/commits/merge-theme-and-install) branch, which incorporates work on install/update split by @bpinto. It would be interesting if you could rebase your fixes into this branch and push into this PR!!

**Comment by scorphus** [comment]
Closing this one in favor of work being done in [merge-theme-and-install](https://github.com/derekstavis/oh-my-fish/commits/merge-theme-and-install). Thanks, @derekstavis.

**Pull request closed without merging**
