### PR TITLE
Get when a file was deleted.

### PR DESCRIPTION
**Pull request by damani42**
When working on a large project and maintaining several branches, it is
intersting to be able to know from which branch a file was deleted.

### CODE REVIEW

**Comment by damani42** [comment]
I would like to know if it's possible to have a review please?

**Comment by bobthecow** [comment]
This isn't really the sort of thing `lib/git` is meant for. These are core libraries used internally by OMF for managing packages.

The ideal place to put things like this is in a package (which can then be added to OMF, and managed by these core libraries 😛).

**Comment by faho** [comment]
Another that was basically already rejected. I'd close it and add it to a git-util plugin or something?

**Comment by scorphus** [comment]
Dear @damani42,

Thank you so much for taking the time to contribute.

I have a suggestion. Your solution is useful not only for OMF and Fish users but Git users in general. So, I suggest you publish it as a git subcommand along with others under such topic: https://github.com/topics/git-subcommand. That way, many more users would benefit from it 🙂

**Pull request closed without merging**
