### PR TITLE
Fishbone theme for fish shell managed by Oh my fish

### PR DESCRIPTION
**Pull request by pantuza**
Hi, 

I've created a theme called Fishbone.  As suggested in Oh my fish [documentation](https://github.com/oh-my-fish/oh-my-fish#omf-submit-pkgname-url), I am sending you a Pull Request to update themes registry.

I've tested theme using: 

* omf submit
* omf doctor
* omf install

Here is a link to [Fishbone theme](https://github.com/pantuza/fishbone)

Congrats for Oh my fish project!  It really rocks : )

### CODE REVIEW

**Comment by scorphus** [comment]
Awesome theme, @pantuza! 👏 👏 👏   Also very tidy! 👍 

Would you like to jump aboard Oh-My-Fish community and bring your theme under the project's umbrella?

There're some minor issues to be addressed, though. Gimp file and GIF animation – which rocks, I must say – should be moved to a separate branch, other than `master`. Doing it so, those files would not be copied when the repo is cloned in every user's machine.

**Comment by scorphus** [comment]
I anticipated and created the repo: https://github.com/oh-my-fish/fishbone 😉  You already have admin rights!

Welcome aboard!

**Comment by pantuza** [comment]
Thank you @scorphus, I've pushed files to the new repository. Also, as you have suggested, I've moved animation.cxf and fishbone.gif to a separated branch called animation.

What about the old repository, should we remove it? Since there is an official one now? 

Regards o/

**Comment by scorphus** [comment]
Ouch, I forgot to prepend the repository name with `theme-`, sorry. I fixed it. Can you please update the commit and make it point to `https://github.com/oh-my-fish/theme-fishbone`?

> […] What about the old repository, should we remove it? Since there is an official one now?

Yup! Feel free to do so.

**Comment by scorphus** [comment]
@pantuza: Do you mind squashing those three commits into one? So we can get a cleaner history and a single commit for this new feature 😃

**Comment by pantuza** [comment]
Hey @scorphus ,

Commits squashed and old repository removed. :smile: 

Now, registry points to [theme-fishbone](https://github.com/oh-my-fish/theme-fishbone)

**Comment by scorphus** [comment]
image


YAY! 🎉  Thank you, @pantuza!

**Pull request merged**
