### PR TITLE
init: rewrite init process

### PR DESCRIPTION
**Pull request by derekstavis**
Now use pure globbing to generate 100% valid function and
completion paths, effectively splitting the init process in two
steps, one which paths are added, and other when initialization
is done (sourcing init).

This initialization code introduces a new interface for
`init.fish` hook, which deprecates the previously used event
model. The new interface injects three variables into `init.fish`:
path, package and bundle. This variables can be used by the
package to autoload paths, use bundled files, etc.

Also supports key bindings by sourcing
$OMF_CONFIG/key_bindings.fish and also key_bindings.fish in
packages (plugins and themes) root directories. This is done
when fish_user_key_bindings is called.

### CODE REVIEW

**Comment by coderstephen** [comment]
Wow, just the code looks so much better and more efficient! Great job with this, @derekstavis!

**Comment by coderstephen** [comment]
I have no issues when running this change. Everything appears to be working excellently without errors, and it starts up _drastically_ faster. Like, it's amazing. Great work on all of this!

**Comment by coderstephen** [comment]
What is the progress on this? Are we reaching merging time?

**Comment by derekstavis** [comment]
I have updated this branch to reflect the changes introduced by `leaner-init` branch, which undergone some structural changes, as the removal of `initialize` function.

**Comment by derekstavis** [comment]
@oh-my-fish/docs pleaser review docs - It was done using Google Translate

**Comment by demidovakatya** [comment]
@derekstavis 
> pleaser review docs - It was done using Google Translate

what do you mean?

**Comment by derekstavis** [comment]
Sorry for my brevity, I was on mobile. This PR touches translated docs. I've done an automatic translation from English to other languages using Google Translate. I'm asking @oh-my-fish/docs team to review the changes contained on this PR.

**Comment by demidovakatya** [comment]
@derekstavis, thanks for your explanation! I can translate the changes to Russian, is it needed?

**Pull request merged**
