### PR TITLE
Add jump plugin repo

### PR DESCRIPTION
**Pull request by iax7**
Jump plugin was added back

### CODE REVIEW

**Comment by bpinto** [comment]
The plugin itself doesn't seem to work. It needs to be converted to the new architecture. Could you open a PR there upgrading it?

**Comment by iax7** [comment]
There's already a pull request for that, It seems to work fine.
https://github.com/oh-my-fish/plugin-jump/pull/3

**Comment by bpinto** [comment]
@iax7 could you rebase your commit so we can merge?

**Comment by derekstavis** [comment]
:+1:

**Comment by iax7** [comment]
I think is ready now.

**Comment by derekstavis** [comment]
Ops! Can you use `git rebase` instead? This way we avoid the _"Merge branch 'master' into master"_ message.

**Comment by iax7** [comment]
How can I get rid of that last commit?

**Comment by derekstavis** [comment]
You can always undo the last commit using `git reset --hard HEAD^`.

**Comment by iax7** [comment]
but that is just locally.

**Comment by derekstavis** [comment]
To update the PR branch just push with `-f`.

**Comment by derekstavis** [comment]
Thanks!! :+1: for the merge @bobthecow @bpinto

**Pull request merged**
