### PR TITLE
Add Visual Studio Code plugin

### PR DESCRIPTION
**Pull request by mathiasvr**
Command line for Visual Studio Code

### CODE REVIEW

**Comment by derekstavis** [comment]
Hi! Would you like to transfer the repository to Oh My Fish organization? Thia way we centralize all plugins, easing the search. You continue as the owner of the repository and the work. If you do want, please rename the repository to `plugin-vscode` and transfer it to `oh-my-fish`, updating the PR accordingly and I'll promptly add you as an admin and merge the PR.

**Comment by mathiasvr** [comment]
Hi, no problem - I have updated the PR and are ready to transfer the repo :+1:

**Comment by derekstavis** [comment]
Would you mind squashing the PR into a single commit? As soon as you do it and transfer the repository I will merge the PR.

**Comment by mathiasvr** [comment]
Okay, just needed to add squashing to my git skills :smile:

**Comment by derekstavis** [comment]
Awesome!! That's the meaning of community! Always learn something new!

**Comment by derekstavis** [comment]
Are you ready @mathiasvr? I'm just waiting the transfer to merge the PR.

**Comment by mathiasvr** [comment]
Oh sorry, I cannot transfer without admin rights in the organization.

**Comment by derekstavis** [comment]
Oh, I wasn't aware of that. I have allocated the repository and made you admin so you can push to it.

**Comment by derekstavis** [comment]
After pushing to organization's one you can remove your user's copy if you want. That would be great to avoid duplication.

**Comment by mathiasvr** [comment]
Done!

**Comment by derekstavis** [comment]
Thanks! And welcome to Oh My Fish organization :tada:

**Pull request merged**
