### PR TITLE
Improve grammar and punctuation for docs/RU

### PR DESCRIPTION
**Pull request by demidovakatya**

### CODE REVIEW

**Comment by sobolevn** [comment]
Well, it's way better now!

**Comment by bobthecow** [comment]
Thanks!

**Comment by demidovakatya** [comment]
@sobolevn, hey, I'm searching for examples of nicely written documentation in Russian, so if you've seen something like that, please let me know

**Comment by sobolevn** [comment]
@demidovakatya np

**Comment by derekstavis** [comment]
Cool! Thanks!

**Comment by derekstavis** [comment]
Would you mind rebasing this PR on master before I merge it? If you need help, feel free to join our Slack, and I will be glad to help!

**Comment by bobthecow** [comment]
No need to rebase. Thanks for the updates!

**Pull request merged**
