### PR TITLE
Add ru-RU docs

### PR DESCRIPTION
**Pull request by VEINHORN**

### CODE REVIEW

**Comment by derekstavis** [comment]
Looks pretty awesome to me! As soon as you are, I'm ready to merge! :+1:

**Comment by demidovakatya** [comment]
Hey @VEINHORN, thanks :+1: 

I would like to fix some lines there. Could you guys mention me as soon as you finish merging? :)

**Comment by derekstavis** [comment]
@demidovakatya Perhaps you would like to comment the diff so @VEINHORN can fix in this PR?

**Comment by VEINHORN** [comment]
@derekstavis Hey. I updated several links in last commit. But I couldn't find links to _pkg-pyenv_ that are in FAQ.

**Comment by derekstavis** [comment]
@demidovakatya could you point the fixes you wanted to see inside this PR? It would be better if we merge just one PR with Russian translations ready instead of creating another PR with fixes.

**Comment by demidovakatya** [comment]
sure, in a couple of hours

**Comment by oranja** [comment]
Hi people, it's a shame for this good work to keep drying like this.

@demidovakatya, do you think you can get your fixes in anytime soon?
If not, one more commit at a later time won't hurt. So I don't see why keep @VEINHORN's hard work on hold for so long.

**Comment by coderstephen** [comment]
:+1: For this. @VEINHORN can you do a rebase so we can get your hard work merged?

**Comment by bobthecow** [comment]
I'm going to go ahead an merge this. We don't need a rebase first.

@demidovakatya @VEINHORN if you've got any further updates, please open a PR :)

**Comment by demidovakatya** [comment]
:+1: thanks a lot! I'll contribute as soon as I have some free time.

**Comment by VEINHORN** [comment]
@oranja @coderstephen @bobthecow Thank you guys for merging. :+1:

**Comment by bobthecow** [comment]
Thanks for your contributions :)

**Comment by bobthecow** [comment]
We're considering starting a docs team on the OMF org, to make it easier to coordinate around updating docs and translations as changes come in. Does this seem reasonable? Would you two mind being pinged when, for example, something like #266 comes along which updates README.md?

**Comment by demidovakatya** [comment]
not at all

**Comment by VEINHORN** [comment]
@bobthecow Good idea.

**Comment by bobthecow** [comment]
Great! I've invited you both to be members of the @oh-my-fish/docs team :)

**Comment by demidovakatya** [comment]
Yay! :balloon:

**Pull request merged**
