### PR TITLE
Remove plugin or theme as URL from bundle

### PR DESCRIPTION
**Pull request by scorphus**
Please review, @all.

### CODE REVIEW

**Comment by scorphus** [comment]
Looks like this one is already fixed in $15

**Comment by bpinto** [comment]
In https://github.com/oh-my-fish/oh-my-fish/pull/16 you mean?

**Comment by scorphus** [comment]
None, actually. It is needed, at least in my case. @all: Can you confirm?

With this commit included:
screen shot 2015-09-06 at 7 20 53 pm

**Comment by bpinto** [comment]
:+1: I misunderstood the problem, this is something @derekstavis were talking another day. :D

**Comment by derekstavis** [comment]
Closing as this was included in fixes merged in #25.

**Pull request closed without merging**
