### PR TITLE
Add nelsonjchen theme to db

### PR DESCRIPTION
**Pull request by nelsonjchen**
This is a theme that's based off of the re5et theme from oh-my-zsh with some modifications for my preferences.

### CODE REVIEW

**Comment by bpinto** [comment]
It looks very nice, could you rebase? I have just merged a few PRs (making the git log history quite ugly) and would like to go back to a single history line. :D

**Comment by nelsonjchen** [comment]
Sure! 

In the future, I'm pretty sure there's a bot out on GitHub you can use to do what you want.

**Comment by bpinto** [comment]
FIND IT TO ME PLLLLLEEEEEEEEEEEEEEEEAAAAAAAAAAAAAAAASSSSSSSSSSSEEEEEEEEE!

**Comment by nelsonjchen** [comment]
k,k k kk, i 'll keep an eye out!

**Comment by nelsonjchen** [comment]
If the Rust project can have something like Homu, there's got to be something like what you want.

**Comment by nelsonjchen** [comment]
Rebased.

**Comment by bpinto** [comment]
Merged! Thanks :+1:

**Pull request merged**
