### PR TITLE
Add apt plugin to db

### PR DESCRIPTION
**Pull request by coderstephen**
This adds [my apt plugin](https://github.com/coderstephen/plugin-apt) to the general package database. This is a package that I've developed and tweaked over the years that started out as a bash script. When I switched to Fish a few years ago, this script was rewritten in Fish and became a function, which became an OMF plugin when I started using the framework several months ago.

I originally kept the package inside my personal dotfiles repo, but I figured that other Debian or Ubuntu users might benefit from the package as well.

Thoughts on the package?

### CODE REVIEW

**Comment by derekstavis** [comment]
Great! :+1:

**Comment by bobthecow** [comment]
Should we encourage moving repos like this into the omf org as well?

**Comment by bpinto** [comment]
I'd like to, but how?

**Comment by bobthecow** [comment]
CONTRIBUTING.md :)

**Comment by bpinto** [comment]
PR it? :)

**Comment by coderstephen** [comment]
Yeah, I wasn't sure where one should put the package repo if they aren't part of the omf organization.

**Comment by bobthecow** [comment]
One should become part of the omf organization ;)

**Pull request merged**
