### PR TITLE
Revamp current logo, use SVG version on README

### PR DESCRIPTION
**Pull request by derekstavis**
This PR replaces the PNG logo by a SVG one, closing #131

### CODE REVIEW

**Comment by bpinto** [comment]
We could keep the `.png` file. I thought we might want to add the `.psd` file, but better not.

**Comment by derekstavis** [comment]
The SVG file is the best source for generating raster files. I see no reason to keep the PNG version if we don't use it anywhere :)

**Comment by bpinto** [comment]
We could use. The file is already on git, removing it won't decrease the repository size.

**Comment by derekstavis** [comment]
Ok. Should I update it based on a SVG version rasterisation?

**Comment by derekstavis** [comment]
Here we go!

**Comment by scorphus** [comment]
I have finished polishing the SVG file. These are the differences after all the angles were correctly balanced and curves perfectly adjusted:

diff

I still need to optimize it, remove some unnecessary stuff from it. Please bear with me while I do so. Thanks.

**Comment by derekstavis** [comment]
Be sure that the logo is symmetric! We don't want to swap a crooked logo by another one!

**Comment by scorphus** [comment]
Oh, sure. That's exactly one of the things that it **wasn't**, symmetric. I'll push to this very branch as soon as I'm done. Ok?

**Comment by derekstavis** [comment]
I'd prefer heading to #139 or posting the result here to discuss before pushing to the branch.

**Comment by scorphus** [comment]
Works for me.

**Comment by derekstavis** [comment]
Nice. Thanks! :+1:

**Comment by scorphus** [comment]
@all: Sorry for taking so long. Please, have a look. Thanks!

**Comment by derekstavis** [comment]
Indeed more aligned, looks almost the same of my original Illustrator file (before grid alignment). It happens that you just added the floating point, which I have _intentionally_ removed for alignment and rendering reasons.

Anyway, in the meantime I have wondered about what adjustments could be done in PR's current logo and came with a better version whose alignment is based on iOS icon grid. I have worked harder to ensure [grid aligning](https://helpx.adobe.com/illustrator/using/drawing-pixel-aligned-paths-web.html) by design, instead of a [post-process task](https://github.com/svg/svgo), as I have done the first time.

As soon as I can get hands on my computer I will post it here.

**Comment by derekstavis** [comment]
Here we go. Some design points that were worked out on this version:

- Image size: 1024 x 1024
  - 8's multiple for better resizing
- Pixel alignment by design
  - [Better rendering](http://www.adobepress.com/articles/article.asp?p=1929168&seqNum=5) when resized
- Fish size and position based on a grid
  - [iOS icon grid](http://40.media.tumblr.com/5c09fe1d9c083e93850dfca1d6d6342b/tumblr_moc979zqpS1qcbqvco1_1280.png)
- Background corner rounding: 48px

URLs now use rawgit service to serve the SVG logo with right Content-Type. For preview reasons they currently point to this repo user/branch, but will be adjusted before the merge.

**Comment by bpinto** [comment]
ping @scorphus 

I like that the link is using rawgit which means we can improve it and still change the logo on all READMEs.

**Comment by bpinto** [comment]
:+1:

**Comment by scorphus** [comment]
Remarkable job, @derekstavis! I've just one thing to note. I think these four points **can** be removed without losing **anything**:
clip

Aside from that, it rocks!

BTW, I'm gonna ask my fellow designers to have a look and see what they say about it, maybe they have something to contribute.

Thanks!

**Comment by derekstavis** [comment]
The bigger circled points could be removed. I will give a look at home. The other ones are needed for pixel grid aligment, in a way we don't get broken widths.

**Pull request merged**
