### PR TITLE
[WIP] Fix the screenshot source of pure theme.

### PR DESCRIPTION
**Pull request by shuuji3**
Hi, I fixed the image link of pure's screenshot.
The origin of the image is from here: https://github.com/sindresorhus/pure

### CODE REVIEW

**Comment by bobthecow** [comment]
This file is automatically generated from the README files in the individual projects. Changing it here won't be permanent, because it'll just be overwritten the next time someone re-generates the file.

https://github.com/oh-my-fish/oh-my-fish/blob/master/tools/generate-themes-doc.fish

A better answer would be to update the script to handle relative src paths and rewrite them to use githubusercontent.com.

**Comment by shuuji3** [comment]
Oh, I didn't notice the script. Thanks for pointing out that.
I'll investigate the script in my spare time and fix the problem.

**Comment by scorphus** [comment]
This issue had to be fixed as in ac1c980a76116bcaccb75b010b02f3b44c6bb8be. Nonetheless, thank you for contributing.

**Comment by shuuji3** [comment]
Sorry for leaving for a long time...:pray: I'm glad to hear that fix! Thank you.

**Pull request closed without merging**
