### PR TITLE
Docs: Fix Markdown syntax (paragraphs)

### PR DESCRIPTION
**Pull request by takidelfin**
# Description

Some paragraphs are rendered incorrectly in [Themes.md](./docs/Themes.md).
I fixed Markdown syntax by adding spaces after *#-paragraphs*

Fixes # N/A

**Environment report**
N/A

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/oh-my-fish/oh-my-fish/blob/master/CONTRIBUTING.md#code-style) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by bobthecow** [comment]
This file is auto-generated from the readme files from all the themes, so the next time it's generated your fix will go away. We need to fix the markdown in `es` theme's readme: 

https://github.com/oh-my-fish/theme-es

**Review by faho — APPROVED** [review]
LGTM

**Review by faho — CHANGES_REQUESTED** [review]
This was already done in theme-es in https://github.com/oh-my-fish/theme-es/commit/2e11628a43e5f0b55cceda0311cf5a5881111f70, the file should be regenerated.

**Comment by scorphus** [comment]
Then, let's concentrate on #795 as the issue to be solved. 

Thanks for taking the time to contribute, @takidelfin.

**Pull request closed without merging**
