### PR TITLE
add pkg export

### PR DESCRIPTION
**Pull request by jcouyang**

### CODE REVIEW

**Comment by derekstavis** [comment]
By OMF convention, the repository name must be prefixed with just "plugin". In this case the correct URL should be `https://github.com/jcouyang/plugin-export`. You also don't need to prepend `.git` :)

**Comment by derekstavis** [comment]
Ah, don't forget to squash your commits into a single one  :shipit:

**Comment by derekstavis** [comment]
Awesome! :ship: it @bpinto!

**Comment by bpinto** [comment]
:+1:

**Pull request merged**
