### PR TITLE
Extract _write_bundle to omf.persist

### PR DESCRIPTION
**Pull request by bpinto**
- Add support for persisting theme information.
- Use documented private function naming scheme.

### CODE REVIEW

**Comment by bpinto** [comment]
@oh-my-fish/core any comments here?

**Comment by scorphus** [comment]
Trying this one at this moment.

**Comment by derekstavis** [comment]
Works OK for me :+1:

**Comment by scorphus** [comment]
:+1: although some conflicts with #21 may arise, but nothing we can't solve

**Pull request merged**
