### PR TITLE
add pastfish theme

### PR DESCRIPTION
**Pull request by chgu82837**
add my theme: https://github.com/chgu82837/PastFish

### CODE REVIEW

**Comment by bpinto** [comment]
The repository name needs to be prefixed with `theme-` e.g. `https://github.com/chgu82837/theme-PastFish`

**Comment by bpinto** [comment]
Could you squash and rebase your branch so we can merge? Thanks!

**Comment by derekstavis** [comment]
Hey @chgu82837, awesome theme idea!! I loved it! Would you mind generating theme documentation by running the script `tools/generate-themes-doc.fish` script and adding the generated documentation to this PR?

**Comment by chgu82837** [comment]
The CI check failed, does this mean I have to update the readme on my own?

**Comment by chgu82837** [comment]
@derekstavis thank you for telling me how to update the theme-doc. I was confused by the CI check XDD

**Comment by derekstavis** [comment]
Awesome!! I'm OK for it @bpinto :+1:

**Comment by bpinto** [comment]
Thanks @chgu82837

**Pull request merged**
