### PR TITLE
registry: add hasanozgan/theme-lambda

### PR DESCRIPTION
**Pull request by hasanozgan**

### CODE REVIEW

**Comment by oranja** [comment]
It seems like you modified your **Readme.md** after submitting this PR.
You will have to run `tools/generate-themes-doc.fish` again and push.
And please squash the commits into one.

(I know because I've been there myself just a couple of days ago :confused:)

**Comment by oranja** [comment]
Also, I would vote in favor of renaming **[l](/oh-my-fish/theme-l)** to **lambda-compact**, as it is very similar to [lambda](/hasanozgan/theme-lambda) in concept, and easy to miss in its current name.

**Comment by derekstavis** [comment]
I would not rename themes, as it could affect user bundles.

**Comment by oranja** [comment]
Point taken.

**Comment by hasanozgan** [comment]
thank you feedback, I run tools/generate-themes-doc.fish

**Comment by derekstavis** [comment]
you mind squashing into a single commit?

**Pull request merged**
