### PR TITLE
Fix outdated project information

### PR DESCRIPTION
**Pull request by andrelfpinto**
@bpinto não faz nada direito!

### CODE REVIEW

**Comment by bucaran** [comment]
@andrelfpinto Obrigado!

**Comment by andrelfpinto** [comment]
Your welcome.
I hope you didn't mind me speaking Portuguese, but it was a direct joke at @bpinto.

**Comment by bucaran** [comment]
:smile: What is direito?

**Comment by bpinto** [comment]
:D :D

@bucaran "correct"

**Comment by bucaran** [comment]
@bpinto Think I got it.

**Pull request merged**
