### PR TITLE
bundle: make contents unique when adding and installing bundle

### LINKED ISSUE #42: Using omf install duplicates lines in bundle
Starting with no plugins installed and two things defined in the bundle file.

```
> cat .config/omf/bundle
theme bobthefish
package z
```

Now I'm running `omf install` to install my theme/packages.
```
> omf install
Installing bobthefish theme...
✔ theme bobthefish successfully installed.
Installing z package...
✔ package z successfully installed.
```

After that both things are getting added to the bundle (again)
```
> cat .config/omf/bundle
theme bobthefish
package z
theme bobthefish
package z
```

I'm using fish 2.2.0 and oh-my-fish 4b0dbc2

### PR DESCRIPTION
**Pull request by derekstavis**
This comes to fix #42 and also makes code more homogeneous by reusing code patterns.

### CODE REVIEW

**Comment by bpinto** [comment]
What I don't like about sorting is that maybe a plugin requires another to be loaded before. I am not sure how to properly handle it yet. But it might be that the ordering should be irrelevant and we need to find a proper way to handle this scenario.

**Comment by derekstavis** [comment]
Currently the bundle file isn't what is used to load packages. We need a dedicated solution for dependency tracking, and I think that it should be addressed together with the changes that #8 will implement, as this way we "break" the API in a row rather than sparse.

**Comment by bobthecow** [comment]
:+1: looks good to me.

**Comment by bpinto** [comment]
:+1:

**Comment by derekstavis** [comment]
I've rebased the PR on master, merging it.

**Pull request merged**
