### PR TITLE
Add slavic-cat theme

### PR DESCRIPTION
**Pull request by yangwao**
omf-theme-slavic-cat

# omf theme slavic-cat

## Features

 * Minimal look
 * Display branch for Git projects
 * Git project dirty status indicator *meow* **(R,C,A,U,M,?)** *meow*
 * Fish shell vi mode indicator
 * Next line prompt

### CODE REVIEW

**Comment by derekstavis** [comment]
Hey! Sorry for the delay. Can you please rebase your commit without docs/Themes.md? I'd like to give a bump myself after merging the two pending theme PRs! Thanks!

**Comment by yangwao** [comment]
I haven't done rebase PR before, hope I made it right.
You will then submit theme into Themes.md?

**Comment by sagebind** [comment]
@yangwao The Themes.md file is automatically generated using a script, which we will run after we merge in the themes.

**Comment by yangwao** [comment]
From where is it generated? From theme repository?

**Comment by sagebind** [comment]
Yep, it basically combines the READMEs from all theme repositories into one big document.

**Comment by derekstavis** [comment]
Awesome! Thanks @yangwao!! 👍

**Comment by yangwao** [comment]
Bump, looks like my theme is missing in https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md
Was it generated already? But I can it install it as well.

**Comment by sagebind** [comment]
It is regenerated in #472, but hasn't been merged yet. It's still kind of a manual process.

**Pull request merged**
