### PR TITLE
Replace gitter with slack

### PR DESCRIPTION
**Pull request by bpinto**
We are using slackin (https://github.com/rauchg/slackin) to automatically accept people's invitation.

### CODE REVIEW

**Comment by derekstavis** [comment]
Maybe this badge looks better?



image source:

https://img.shields.io/badge/slack-join%20the%20chat-38978D.svg?style=flat-square

**Comment by derekstavis** [comment]
In the future we could add the possibility of tweaking badges to slackin

**Comment by bpinto** [comment]
I'd rather have the count on the badge and work on the badge in the future.

The count works as a way to show there are people online in the community in case you need help.

**Comment by derekstavis** [comment]
So let's go for it :+1:

**Comment by derekstavis** [comment]
Ah, don't forget to update README links too!!

**Comment by bpinto** [comment]
Which links?

**Pull request merged**
