### PR TITLE
Add wttr plugin to omf

### PR DESCRIPTION
**Pull request by pedrosnk**
Add a wttr plugin to omf that interfaces with wttr.in service and shows weather information

### CODE REVIEW

**Comment by derekstavis** [comment]
Hey @pedrosnk, would you like to join Oh My Fish organization? I can allocate a repository inside the organization so you can move your work and join us!

**Comment by pedrosnk** [comment]
Yes, I'd like to.
Thanks for the invite :)

**Comment by derekstavis** [comment]
Hey @pedrosnk, I just imported your repository into https://github.com/oh-my-fish/plugin-wttr and made you an admin. You have full control of it :)

Please update this PR accordingly and I will merge it instantaneously! Also be sure to keep your mainline work inside organization's repository and to remove your repository to avoid confusion :)

**Comment by pedrosnk** [comment]
Thanks @derekstavis . just updated it.
:heart:  💗  💙

**Comment by scorphus** [comment]
@pedrosnk: Thank you, my friend! ☕

**Comment by derekstavis** [comment]
Welcome to the organization @pedrosnk!

**Pull request merged**
