### PR TITLE
Add getopts pkg

### PR DESCRIPTION
**Pull request by vincentjames501**

### CODE REVIEW

**Comment by bpinto** [comment]
We already have it over here: https://github.com/oh-my-fish/plugin-getopts/

**Comment by vincentjames501** [comment]
D'oh! Shall I update it to that URL?

**Comment by bpinto** [comment]
Yep!

**Comment by vincentjames501** [comment]
Done. Cheers!

**Comment by bpinto** [comment]
Could you squash and rebase? Thanks!

**Comment by vincentjames501** [comment]
Should be a clean merge now :)

**Comment by bpinto** [comment]
Thanks!

**Pull request merged**
