### PR TITLE
New theme: shellder

### PR DESCRIPTION
**Pull request by simnalamburt**
[Shellder](https://github.com/simnalamburt/shellder)
---------
> Things are beautiful if you love them. *[Jean Anouilh]*

Shellder is a fork of agnoster, with smarter functionalities

1. No solarized colorscheme
2. Distinguishs untracked, unstaged and staged change.
3. [etc](https://github.com/simnalamburt/shellder/commits/master)

Please add this to the default db!

[Jean Anouilh]:   https://en.wikipedia.org/wiki/Jean_Anouilh

### CODE REVIEW

**Comment by lfiolhais** [comment]
The name of your repository must be either `theme-shellder` or the more recent `omf-theme-shellder`.

**Comment by simnalamburt** [comment]
@lfiolhais It's aliased as `theme-shellder`. Try below:

https://github.com/simnalamburt/theme-shellder
https://github.com/simnalamburt/omf-theme-shellder

**Comment by derekstavis** [comment]
Thanks for the submit!! If you are on Linux you can run `tools/generate-themes-doc.fish` to add your theme README to our [main repository index](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md). This will also make Travis test pass, so I can merge it as soon as you push the docs. If you aren't on Linux I can do it here.

**Comment by lfiolhais** [comment]
@simnalamburt :+1:

**Comment by simnalamburt** [comment]
@derekstavis Sorry I didn't know that. Maybe we should update [CONTRIBUTING.md](https://github.com/oh-my-fish/oh-my-fish/blob/master/CONTRIBUTING.md) or something.

**Comment by derekstavis** [comment]
Merged!! We surely need to update our contributing guide, but we're actually quite busy with some housekeeping so we can tag a 1.0 release, where we will probably revamp all the documentation with more detailed information. Thanks for your contribution!

**Pull request merged**
