### PR TITLE
Remove `basename` from core library

### LINKED ISSUE #151: Remove `basename` from core library
I have no records of `basename -s` being actually used anywhere in the project.

### PR DESCRIPTION
**Pull request by bpinto**
The features added by this function are not used anywhere.

Fix #151

### CODE REVIEW

**Comment by bobthecow** [comment]
:+1:

**Comment by derekstavis** [comment]
:+1:

**Comment by derekstavis** [comment]
So long and thanks for all the overhead

**Comment by bpinto** [comment]
lmao

**Pull request merged**
