### PR TITLE
add powerline

### PR DESCRIPTION
**Pull request by iamruinous**
Added powerline plugin

### CODE REVIEW

**Comment by bpinto** [comment]
@iamruinous could you rebase it?

**Comment by bpinto** [comment]
Could you also rename your repository to `plugin-powerline`? It makes it easier to develop some functionalities when the packages on the database follow the same pattern.

**Comment by derekstavis** [comment]
You can also remove unused stuff: `uninstall.fish` file, `functions` and `completions` directories.

**Comment by jrobeson** [comment]
I'm a little confused, but does the plugin actually do anything yet?

**Comment by bpinto** [comment]
There are some command executed in the `init.fish`.

**Comment by bpinto** [comment]
ping @iamruinous

**Comment by bpinto** [comment]
Dead. :(

**Pull request closed without merging**
