### PR TITLE
Convert plugin to new OMF architecture

### PR DESCRIPTION
**Pull request by mquinnv**
plugin was compatible with new architecture without modification. updated pkg db

### CODE REVIEW

**Comment by derekstavis** [comment]
Thanks!! Could you please use `https` URL on both files and rename the commits to state the added plugin? Follow the same commit message naming `Update db with converted <plugin name here> plugin`.

**Comment by bpinto** [comment]
ping @mquinnv

**Comment by mquinnv** [comment]
ok, think i've got it this time!

**Comment by derekstavis** [comment]
Would you mind squashing the merge message?
You can use `git edit` to remove it then use `git rebase oh-my-fish/master master`

**Comment by mquinnv** [comment]
ok, so i needed to have rebased instead of pulling earlier. your suggested command didn't work. git didn't think that HEAD~3 existed. i just went ahead and reset my repo to your head and redid the commits. should be what you need this time

**Comment by bpinto** [comment]
Thanks!!

**Pull request merged**
