### PR TITLE
Add ssh-config.d plugin into database

### PR DESCRIPTION
**Pull request by rominf**
Add [ssh-config.d](https://github.com/rominf/oh-my-fish_plugin-ssh-config.d) plugin to database

### CODE REVIEW

**Comment by lfiolhais** [comment]
The link you added returns a 404. Is this the link you wanted to add: https://github.com/rominf/oh-my-fish_plugin-ssh-config.d ?

**Comment by derekstavis** [comment]
@rominf I will create the repository inside Oh My Fish organization for you and add you as an admin.

**Comment by derekstavis** [comment]
Here we go. Push your work here and I can merge this PR as soon as possible: https://github.com/oh-my-fish/plugin-ssh-config.d

**Comment by rominf** [comment]
@derekstavis done. Thank you!

**Comment by derekstavis** [comment]
Cool! Merging!

**Pull request merged**
