### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**

### CODE REVIEW

**Comment by faho** [comment]
My dutch is quite rusty, but this seems like an acceptable first pass. LGTM!

**Review by faho — APPROVED** [review]

**Review by scorphus — APPROVED** [review]

**Comment by bobthecow** [comment]
Thanks!

**Comment by scorphus** [comment]
Yes! Thanks, @Vistaus 👍

**Comment by Vistaus** [comment]
No problem, guys, happy to help out! 🙂

**Pull request merged**
