### PR TITLE
add mokou to the theme registry

### PR DESCRIPTION
**Pull request by tentakel**
https://github.com/tentakel/mokou

### CODE REVIEW

**Comment by derekstavis** [comment]
Hi! Would you like me to allocate a repository inside Oh my Fish organization so you can join the community as an administrator of that repo and move mainstream development there?

**Comment by tentakel** [comment]
sure!

**Comment by derekstavis** [comment]
You are now an adming at https://github.com/oh-my-fish/theme-mokou. Please update this PR accordingly and remove the original repository!

**Comment by tentakel** [comment]
should be updated

**Comment by derekstavis** [comment]
Cool! Welcome to the organization! 👍 
Merging!

**Pull request merged**
