### PR TITLE
Streamlined Errors Message

### PR DESCRIPTION
**Pull request by lfiolhais**
When an update fails instead of getting this garble of output:
```
fatal: unable to access 'https://github.com/oh-my-fish/oh-my-fish.git/': Could not resolve host: github.com
Oh My Fish failed to update.
Please open a new issue here → github.com/oh-my-fish/oh-my-fish/issues
fatal: unable to access 'https://github.com/oh-my-fish/theme-default/': Could not resolve host: github.com
Could not update default.
fatal: unable to access 'https://github.com/oh-my-fish/plugin-errno/': Could not resolve host: github.com
Could not update errno.
fatal: unable to access 'https://github.com/lfiolhais/plugin-homebrew-command-not-found/': Could not resolve host: github.com
Could not update homebrew-command-not-found.
fatal: unable to access 'https://github.com/oh-my-fish/plugin-python/': Could not resolve host: github.com
Could not update python.
fatal: unable to access 'https://github.com/lfiolhais/theme-simple-ass-prompt/': Could not resolve host: github.com
Could not update simple-ass-prompt.
fatal: unable to access 'https://github.com/oh-my-fish/plugin-tab/': Could not resolve host: github.com
Could not update tab.
fatal: unable to access 'https://github.com/oh-my-fish/pkg-z/': Could not resolve host: github.com
Could not update z.
```

You simply get this:
```
Oh My Fish failed to update.
Please open a new issue here → github.com/oh-my-fish/oh-my-fish/issues
Could not update default.
Could not update errno.
Could not update homebrew-command-not-found.
Could not update python.
Could not update simple-ass-prompt.
Could not update tab.
Could not update z.
```

### CODE REVIEW

**Comment by oranja** [comment]
The tidiness of the second option is clear to see, but only seldom do I find it reasonable to hide a warning or an error from the user.
There are many reasons that a package might fail to update. This specific error provides a fairly concise and accurate description, if you ask me. As long as the signal-to-noise ratio is high, what's wrong with showing the error details?
I will only cast my vote for such a change if some way to get the error is retained. For example with a debug flag or a log file. Yet even then, I'm still not sure that it doesn't just add more work for the rare cases when something breaks.

Either way, this is just my opinion, and the effort is appreciated regardless. Thank you @lfiolhais.

**Comment by derekstavis** [comment]
Hey! Thanks @lfiolhais!

I like the final result. Less noisy. But I also like @oranja thoughts.
Maybe we could meld both ideas and have an output like this one?:

```
Oh My Fish failed to update.
Please open a new issue here → github.com/oh-my-fish/oh-my-fish/issues
Could not update default: Could not resolve host: github.com
Could not update errno: Could not resolve host: github.com
Could not update homebrew-command-not-found: Could not resolve host: github.com
Could not update python: Could not resolve host: github.com
Could not update simple-ass-prompt: Could not resolve host: github.com
Could not update tab: Could not resolve host: github.com
Could not update z: Could not resolve host: github.com
```

(We could also have different colors for the error messages)

**Comment by lfiolhais** [comment]
Hi @oranja, thank you for the input. I do agree with you that the user should be informed of the error however, for new users this becomes more of a nuisance rather than a helpful and informative warning. That being said I like @derekstavis proposal, it is concise, clean and most importantly informative. A flag could be provided to keep raw errors in.

**Comment by lfiolhais** [comment]
This is the solution I came up with. Could you guys give feedback on it? I'm not particularly fond of global variables but that's the only way I found to have a variable across several functions whilst keeping the same value. :disappointed:

**Comment by lfiolhais** [comment]
Closing, as I don't find this to be a good solution to the problem.

**Comment by oranja** [comment]
@lfiolhais, I'm terribly sorry for keeping you hanging like this.
I don't think that the severity and rarity of this issue justifies a global variable to keep error messages, but if you ever feel like coming back to this (either to convince me of the value or with a different approach), do ping me here or on Slack.
I also feel obliged to declare that I'm just a guy hanging around and trying to help, and I don't call any shots around here. In other words: see my arguments as a service, or just ignore them. I don't mean, and don't have the authority, to be a barrier.

The search functionality (#314) is awesome :+1: :clap:
Hope to keep seeing you around!

**Pull request closed without merging**
