### PR TITLE
Add red-snapper theme

### PR DESCRIPTION
**Pull request by ZuraGuerra**
I added a theme with Git support and an ASCII fish.
https://github.com/ZuraGuerra/theme-red-snapper
fish shell commited

### CODE REVIEW

**Comment by bucaran** [comment]
Hey @ZuraGuerra and thanks for your contribution.

Please commit your changes directly to [this repository](https://github.com/oh-my-fish/red-snapper).

**Comment by ZuraGuerra** [comment]
Done :) Thank you!

**Comment by bucaran** [comment]
:+1:

**Comment by ZuraGuerra** [comment]
Just noticed something! Would you please change the name of the repo to theme-red-snapper? Thanks! :D

**Comment by bucaran** [comment]
My bad. _Done_.

**Pull request closed without merging**
