### PR TITLE
doc support i18n

### PR DESCRIPTION
**Pull request by icyleaf**
Hi, i really love fish and oh my fish, and i want more and more guys change to it, so i think the docs must be support [i18n](https://en.wikipedia.org/wiki/Language_localisation). 

for now, i only translated docs into Simplified Chinese.

### CODE REVIEW

**Comment by bpinto** [comment]
I really really like it, but I don't have the time right now to see how it looks like on the computer. I will have soon though.

**Comment by icyleaf** [comment]
OK, maybe translate fish shell docs is good idea.

**Comment by bpinto** [comment]
@icyleaf don't close it, we are going to merge it! ;)

**Comment by bpinto** [comment]
@icyleaf This is awesome! Would you mind rebasing it so we can merge?

**Comment by bpinto** [comment]
I have manually rebased and merged, thanks @icyleaf

**Comment by bobthecow** [comment]
@icyleaf Thank's for your contributions! We just started a docs team to make it easier to coordinate around updating docs and translations as changes come in. If you'd like to be involved with that, we'd love to have you :)

**Pull request closed without merging**
